### ISSUE TITLE
Extra parenthesis when pretty printing (I think it actually happens earlier in the parser)

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#40]
I have the following issue, let's take for instance this example.

```python
import mappyfile                                                                
from mappyfile.pprint import PrettyPrinter                                      
                                                                         
def _pprint(d, indent=2):                                                       
    pp = PrettyPrinter(indent=indent)                                           
    return pp.pprint(d)                                                         
                                                              
c = """                                                                         
CLASS                                                                           
    EXPRESSION (('[agglo_klas]'='K') OR ('[agglo_klas]'='M'))                   
END                                                                             
"""
                                                       
m = mappyfile.loads(c)                                                          
print _pprint(m)                                                                

m = mappyfile.loads(_pprint(m))                                                 
print _pprint(m)
```

This will result in:

CLASS
  EXPRESSION (( (( '[agglo_klas]' = 'K' )) or (( '[agglo_klas]' = 'M' )) ))
END
CLASS
  EXPRESSION ((( ((( '[agglo_klas]' = 'K' ))) or ((( '[agglo_klas]' = 'M' ))) )))
END

Adding more and more parenthesis after each operation. If I want to use it as an automatic linter for my mapfiles, I want the structure to remain stable between each iteration. Any way we can tune that somewhere?

FYI I was fine with the first EXPRESSION and didn't need to have all these parenthesis added in the first place.

**Comment by geographika** [comment]
The brackets are added in transformer.py:

```
    def expression(self, t):
        return "(%s)" % t[0]
```

You can change to the following to remove them:

```
    def expression(self, t):
        return "%s" % t[0]
```

However they were added to fix an issue with OR expressions - see #7 
When I get a chance I'll see if this can be resolved differently. 
Let me know how you get on.

**Comment by loicgasser** [comment]
ok thank you for the fast answer. This seems fixable.

**Comment by geographika** [comment]
@loicgasser - I recently checked in major refactoring to the transformer and pretty printer. This hopefully fixes this issue. Due to the major changes (quotes removed at transform stage and added later, plus validation checks) there could be other issues. When you get a chance could you test master to see all still works for you?

**Comment by loicgasser** [comment]
Fantastic! Yes my use case is quite extensive, and I ll be able to tell you if this works for me. I ll make a release in my repo and test it out as soon as I find some time.

**Comment by loicgasser** [comment]
I see mainly these 2 errors:

ERROR:mappyfile:The key 'projections' was not found in the JSON schema for 'layer'
ERROR:mappyfile:The key 'maxwidth' was not found in the JSON schema for 'style'

Treating over 900 layers (but I see those every time)

**Comment by geographika** [comment]
@loicgasser - the maxwidth validation error should be fixed in master. Would you be able to post a minimum LAYER definition that causes the "projections" error?

**Comment by loicgasser** [comment]
@geographika I checked and now it works.

I was also adding some properties on the fly and I noticed you changed a couple of things there.

For instance, before we had to do something like

```
layer['metdata']['wms_extent'] = '"2100000 1050000 2850000 1400000"'
```

and now


```
layer['metdata']['wms_extent'] = '2100000 1050000 2850000 1400000'
```

is sufficient. Which is great!

Thumbs up for this huge improvment. But maybe you should add these details in sphinxdoc or your changlog. People might get confused.

Also noticed you forgot to create a release for 0.5.0 on github.

Maybe, I will try to create a vim plugin, might be a fun tool.

**Comment by geographika** [comment]
@loicgasser - I updated the edit examples in the docs - http://mappyfile.readthedocs.io/en/latest/#modifying-values

I'll be updating the docs significantly to highlight some new experimental features in the next months. 

New release tagged for v0.6, also available on pypi. 

Let me know how you get on with this release as there was some extensive refactoring. 
If you have any large Mapfiles that could be made public I can add them to the test suite.

**Comment by loicgasser** [comment]
Hi! Some updates with the changes introduced in 0.5.0. I noticed that:
``POSITION UC`` becomes ``POSITION "UC"`` which makes mapserver crash

The auto detection of strings is nice but it really needs to work. This error is generated after parsing a valid mapfile, which is then transformed into an invalid mapfilr. I didn't test version 0.6.0 yet, I ll let you know if this still fails. I didn't investigate either.

It would be great if you made PR in our own repository so that people following it get a chance to know what changes are introduced.
I ll try to take the time to test it better next week.
